### ISSUE TITLE
No chunk loading in the payapa config

### ISSUE THREAD

**Issue by megatron0001** [moom0o/Papaya#5]
![image](https://user-images.githubusercontent.com/82678869/123968730-690e9680-d9af-11eb-9d39-d83b9ec7e925.png)
![image](https://user-images.githubusercontent.com/82678869/123968825-83e10b00-d9af-11eb-822b-5bb50853a767.png)

**Comment by moom0o** [comment]
https://github.com/moom0o/Papaya/releases/tag/1.1

**Comment by megatron0001** [comment]
Fixed
#tag 1.1
